import { useState } from 'react';
import { AnimatePresence, LayoutGroup, motion } from 'framer-motion';
import { ChevronLeft, ChevronRight, MapPin, Plus, X } from 'lucide-react';
import { calendarDays, events } from '@/data/demo';
import { softSpring } from '@/design/motion';

type View = 'day' | 'week' | 'month';
const hours = ['08:00', '09:00', '10:00', '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00', '18:00', '19:00', '20:00'];
export function CalendarView() {
  const [view, setView] = useState<View>('day');
  const [selected, setSelected] = useState<string | null>(null);
  const selectedEvent = events.find((item) => item.id === selected);
  return <div className="mt-12">
    <div className="mb-6 flex flex-wrap items-center justify-between gap-4"><div className="flex items-center gap-2"><button type="button" data-testid="button-calendar-prev" aria-label="Previous period" className="rounded-lg border border-[hsl(var(--border))] p-2 text-[hsl(var(--muted-foreground))] hover:text-[hsl(var(--foreground))]"><ChevronLeft size={15} /></button><button type="button" data-testid="button-calendar-next" aria-label="Next period" className="rounded-lg border border-[hsl(var(--border))] p-2 text-[hsl(var(--muted-foreground))] hover:text-[hsl(var(--foreground))]"><ChevronRight size={15} /></button><span className="ml-2 text-xs font-semibold">October 24, 2024</span></div><div className="flex items-center border border-[hsl(var(--border))] bg-[hsl(var(--surface)/.5)] p-1">{(['day', 'week', 'month'] as View[]).map((item) => <button key={item} type="button" data-testid={`button-calendar-${item}`} onClick={() => setView(item)} className={`px-3 py-1.5 text-[10px] font-semibold capitalize transition-colors ${view === item ? 'bg-[hsl(var(--secondary))] text-[hsl(var(--foreground))]' : 'text-[hsl(var(--muted-foreground))] hover:text-[hsl(var(--foreground))]'}`}>{item}</button>)}</div></div>
    <LayoutGroup><div className={`${view === 'month' ? 'grid grid-cols-7 gap-px overflow-hidden border border-[hsl(var(--border))] bg-[hsl(var(--border))]' : 'relative border border-[hsl(var(--border))]'}`}>
      {view === 'month' ? <>{calendarDays.map((day, index) => <div key={day} className="min-h-[112px] bg-[hsl(var(--card))] p-2 sm:min-h-[145px]"><p className={`font-mono text-[9px] ${index === 3 ? 'text-[hsl(var(--primary))]' : 'text-[hsl(var(--muted-foreground))]'}`}>{day}</p>{index === 3 && events.slice(0, 2).map((item) => <button type="button" key={item.id} data-testid={`button-month-event-${item.id}`} onClick={() => setSelected(item.id)} className="mt-3 block w-full truncate border-l-2 border-[hsl(var(--primary))] bg-[hsl(var(--secondary))] px-1.5 py-1 text-left text-[9px] font-semibold">{item.title}</button>)}</div>)}</> : <div className={view === 'week' ? 'grid grid-cols-[repeat(7,minmax(92px,1fr))] overflow-x-auto' : ''}>{view === 'week' && calendarDays.map((day, index) => <div key={day} className="border-r border-[hsl(var(--border))] last:border-0"><p className={`border-b border-[hsl(var(--border))] px-3 py-3 font-mono text-[9px] ${index === 3 ? 'text-[hsl(var(--primary))]' : 'text-[hsl(var(--muted-foreground))]'}`}>{day}</p><div className="relative h-[620px]">{hours.map((hour) => <div key={hour} className="h-12 border-b border-[hsl(var(--border)/.5)]" />)}{index === 3 && events.slice(0, 3).map((item, eventIndex) => <EventBlock key={item.id} item={item} index={eventIndex} onSelect={setSelected} selected={selected === item.id} />)}</div></div>)}{view === 'day' && <div className="grid grid-cols-[58px_1fr]"><div>{hours.map((hour) => <div key={hour} className="h-12 border-b border-[hsl(var(--border)/.5)] pr-3 pt-2 text-right font-mono text-[9px] text-[hsl(var(--muted-foreground))]">{hour}</div>)}</div><div className="relative">{hours.map((hour) => <div key={hour} className="h-12 border-b border-[hsl(var(--border)/.5)]" />)}{events.map((item, index) => <EventBlock key={item.id} item={item} index={index} onSelect={setSelected} selected={selected === item.id} />)}</div></div>}</div>}
    </div></LayoutGroup>
    <AnimatePresence>{selectedEvent && <motion.div layout initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: 'auto' }} exit={{ opacity: 0, height: 0 }} transition={softSpring} className="mt-3 overflow-hidden border border-[hsl(var(--primary)/.25)] bg-[hsl(var(--primary)/.06)]"><div className="flex items-start justify-between gap-4 p-5"><div><p className="font-mono text-[9px] uppercase tracking-[.18em] text-[hsl(var(--primary))]">In the day</p><h3 className="mt-2 font-serif text-3xl">{selectedEvent.title}</h3><p className="mt-2 text-xs text-[hsl(var(--muted-foreground))]">{selectedEvent.time}–{selectedEvent.end} · {selectedEvent.location}</p><p className="mt-4 max-w-md text-xs leading-5 text-[hsl(var(--muted-foreground))]">{selectedEvent.description}</p></div><button type="button" data-testid="button-close-event" onClick={() => setSelected(null)} aria-label="Close event" className="rounded-lg p-1.5 text-[hsl(var(--muted-foreground))] hover:bg-[hsl(var(--secondary))]"><X size={15} /></button></div></motion.div>}</AnimatePresence>
    <button type="button" data-testid="button-add-calendar-event" className="mt-5 inline-flex items-center gap-2 text-[11px] font-semibold text-[hsl(var(--primary))]"><Plus size={14} /> Add a moment</button>
  </div>;
}
function EventBlock({ item, index, onSelect, selected }: { item: (typeof events)[number]; index: number; onSelect: (id: string) => void; selected: boolean }) {
  const top = [120, 270, 460, 600][index] ?? 120;
  return <motion.button layoutId={item.id} type="button" data-testid={`button-calendar-event-${item.id}`} onClick={() => onSelect(item.id)} animate={{ top }} transition={softSpring} className={`absolute left-2 right-2 z-10 border-l-2 px-3 py-2 text-left transition-[background,transform] hover:translate-x-0.5 ${item.color === 'warm' ? 'border-[hsl(var(--accent))] bg-[hsl(var(--accent)/.11)]' : 'border-[hsl(var(--primary))] bg-[hsl(var(--primary)/.10)]'} ${selected ? 'ring-1 ring-[hsl(var(--primary)/.5)]' : ''}`} style={{ height: item.title === 'Lunch with Jo' ? 70 : 58 }}><span className="block truncate text-[11px] font-semibold">{item.title}</span><span className="mt-1 flex items-center gap-1 text-[9px] text-[hsl(var(--muted-foreground))]"><MapPin size={9} />{item.time}</span></motion.button>;
}